# Generated by Django 6.0.1 on 2026-07-28 14:42

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0008_book_text_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('text_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('summary_model_name', models.CharField(blank=True, max_length=100)),
                ('embedding_model_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai', to='library.book')),
            ],
            options={
                'verbose_name': 'Book AI',
                'verbose_name_plural': 'Book AI Records',
                'ordering': ['book'],
            },
        ),
    ]
