# Generated by Django 6.0.1 on 2026-08-04 13:38

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('library', '0011_remove_book_text_embedding_book_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_type', models.CharField(choices=[('description', 'Description'), ('summary', 'Summary'), ('enriched', 'Enriched')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='library.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='library.book')),
            ],
            options={
                'verbose_name': 'Book Summary',
                'verbose_name_plural': 'Book Summaries',
                'ordering': ['book'],
            },
        ),
        migrations.DeleteModel(
            name='BookAI',
        ),
        migrations.AddConstraint(
            model_name='bookembedding',
            constraint=models.UniqueConstraint(fields=('book', 'embedding_type'), name='uniq_book_embedding_type'),
        ),
    ]
