# Generated by Django 6.0.1 on 2026-08-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_bookembedding_booksummary_delete_bookai_and_more'),
        ('library', '0011_remove_book_text_embedding_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksummary',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booksummary',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booksummary',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booksummary',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booksummary',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='library.book'),
        ),
        migrations.AddConstraint(
            model_name='booksummary',
            constraint=models.UniqueConstraint(fields=('book', 'prompt_version', 'model_name'), name='unique_book_summary'),
        ),
    ]
