# Generated by Django 6.0.1 on 2026-08-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_booksummary_input_tokens_booksummary_output_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookembedding',
            name='embedding_type',
            field=models.CharField(choices=[('description', 'Description'), ('summary', 'Summary'), ('summary_no_title', 'Summary (No Title)'), ('enriched', 'Enriched')], max_length=20),
        ),
    ]
