apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookclub-ai
  namespace: bookclub
spec:
  replicas: 1

  selector:
    matchLabels:
      app: bookclub-ai

  template:
    metadata:
      labels:
        app: bookclub-ai

    spec:
      containers:
        - name: ai
          image: bookclub-ai:v1.6
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8001

          startupProbe:
            httpGet:
              path: /health
              port: 8001
            periodSeconds: 5
            failureThreshold: 30

          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            periodSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "1"
              memory: "2Gi"