apiVersion: v1
kind: Service

metadata:
  name: bookclub-ai
  namespace: bookclub
spec:
  selector:
    app: bookclub-ai

  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001

  type: ClusterIP
