services:
  web:
    image: 796973519136.dkr.ecr.eu-west-3.amazonaws.com/bookclub:${IMAGE_TAG}
    
    healthcheck:
      test: ["CMD", "curl",  "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

    restart: unless-stopped

    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - static_volume:/app/staticfiles

    env_file:
      - .env
    
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-3
        awslogs-group: bookclub/web
        awslogs-stream: django

  nginx:
    image: 796973519136.dkr.ecr.eu-west-3.amazonaws.com/bookclub:nginx
    restart: unless-stopped

    ports:
      - "80:80"
    
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles

    depends_on:
      - web

    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-3
        awslogs-group: bookclub/nginx
        awslogs-stream: nginx
    
volumes:
  static_volume: