services:
  web:
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-3
        awslogs-group: bookclub/web
        awslogs-stream: django

  nginx:
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-3
        awslogs-group: bookclub/nginx
        awslogs-stream: nginx