apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookclub-production
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SinanErbezci/bookclub.git
    targetRevision: feature/v1.6-eks-migration
    path: k8s/applications/bookclub/overlays/production

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true