apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookclub-django
spec:
  replicas: 2

  selector:
    matchLabels:
      app: bookclub-django
  
  template:
    metadata:
      labels:
        app: bookclub-django

    spec:
      containers:
        - name: django
          image: ...
          ports:
            - containerPort: 8000