apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: django-secrets
  namespace: default
spec:
  provider: aws

  parameters:
    objects: |
      - objectName: "/bookclub/production/DATABASE_URL"
        objectType: "ssmparameter"
        objectAlias: "DATABASE_URL"

      - objectName: "/bookclub/production/DJANGO_SECRET_KEY"
        objectType: "ssmparameter"
        objectAlias: "DJANGO_SECRET_KEY"

      - objectName: "/bookclub/production/OPENAI_API_KEY"
        objectType: "ssmparameter"
        objectAlias: "OPENAI_API_KEY"

  secretObjects:
    - secretName: django-secrets
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: DJANGO_SECRET_KEY
          key: DJANGO_SECRET_KEY
        - objectName: OPENAI_API_KEY
          key: OPENAI_API_KEY