resources:
  - ../../base/django
  - migrate-job.yaml
  - secret-store.yaml
  - external-secret.yaml
  
replicas:
  - name: django
    count: 2

images:
  - name: bookclub-django
    newName: 796973519136.dkr.ecr.eu-west-3.amazonaws.com/bookclub
    newTag: eks-django

configMapGenerator:
  - name: django-config
    literals:
      - DJANGO_ALLOWED_HOSTS=api.sinanerbezci.com
      - AI_SERVICE_URL=http://ai-service:8001